### ISSUE TITLE
Minor edit needed

### ISSUE THREAD

**Issue by kevinkahn** [ScrewLooseDan/softconsole_sensor_alert#1]
Dan,
If you are still using the console and the lightsensor could you make a small edit to your file.  Line 3 needs to now read
import alertsystem.alerttasks as alerttasks

I did some restructuring on to code tree and this caught me.  In the interim I am patching it on any download of a new version so it isn't critical.  Would just clean things up a bit for the long term.

Thanks,
Kevin

**Comment by ScrewLooseDan** [comment]
Thanks Kevin!

I haven't been using my console, but I did update the code as per your suggestion.  If you have a way to test/verify, let me know.  But, I'll consider it closed otherwise.

Dab

**Comment by kevinkahn** [comment]
That got it - won't need the patch now.  Thanks.  Hope it wasn't anything functional with the console that has you not using it these days.  As always, I'm happy to look at issues or new features.  (Finally added picture frame function at another user's prodding.)

Cheers,
Kevin
